# --- !Ups
create table "accounts" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "balance" double not null default 0
);

create table "transfers" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "from" bigint not null,
  "to" bigint not null,
  "amount" double not null
);


# --- !Downs
drop table "accounts" if exists;
drop table "transfers" if exists;
