# --- !Ups
create table "accounts" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "balance" float not null default 0,
  "currency_id" bigint not null default 1
);

# --- !Downs
drop table "accounts" if exists;
